project_id = "wiyfcvypeifbdaqnfgrr"

[functions.device-ingest]
verify_jwt = false

[functions.manage-users]
verify_jwt = true

[functions.device-discovery]
verify_jwt = true

[functions.platform-metrics]
verify_jwt = true
