project_id = "wiyfcvypeifbdaqnfgrr"

[functions.device-ingest]
verify_jwt = false

[functions.manage-users]
verify_jwt = true

[functions.device-discovery]
verify_jwt = true

[functions.platform-metrics]
verify_jwt = true

[functions.populate-device-configs]
verify_jwt = true

[functions.ilq-compute]
verify_jwt = true

[functions.ilq-trend-analyzer]
verify_jwt = true

[functions.ilq-report-generator]
verify_jwt = true
